### ISSUE TITLE
[Qubes] u2mfn Error: Bad return status for module build on kernel: 4.9.13-coldkernel-grsec-1  

### ISSUE THREAD

**Issue by null0x0** [coldhakca/coldkernel#55]
Compiling 'coldkernel-grsec' not working since 4.9.10 up to version 4.9.13. I have no problem  with the 4.8.17 up and running on debian-8 templatevm via qubes-os. Here is the error log:

> make: Entering directory '/usr/src/linux-headers-4.9.13-coldkernel-grsec-1'
  LD      /var/lib/dkms/u2mfn/3.2.3/build/built-in.o
  CC [M]  /var/lib/dkms/u2mfn/3.2.3/build/u2mfn.o
/var/lib/dkms/u2mfn/3.2.3/build/u2mfn.c: In function ‘u2mfn_ioctl’:
/var/lib/dkms/u2mfn/3.2.3/build/u2mfn.c:80:23: warning: passing argument 5 of ‘get_user_pages’ from incompatible pointer type
       (data, 1, 1, 0, &user_page, 0);
                       ^
In file included from /var/lib/dkms/u2mfn/3.2.3/build/u2mfn.c:26:0:
./include/linux/mm.h:1287:6: note: expected ‘struct vm_area_struct **’ but argument is of type ‘struct page **’
 long get_user_pages(unsigned long start, unsigned long nr_pages,
      ^
/var/lib/dkms/u2mfn/3.2.3/build/u2mfn.c:79:9: error: too many arguments to function ‘get_user_pages’
   ret = get_user_pages
         ^
In file included from /var/lib/dkms/u2mfn/3.2.3/build/u2mfn.c:26:0:
./include/linux/mm.h:1287:6: note: declared here
 long get_user_pages(unsigned long start, unsigned long nr_pages,
      ^
scripts/Makefile.build:299: recipe for target '/var/lib/dkms/u2mfn/3.2.3/build/u2mfn.o' failed
make[1]: *** [/var/lib/dkms/u2mfn/3.2.3/build/u2mfn.o] Error 1
Makefile:1495: recipe for target '_module_/var/lib/dkms/u2mfn/3.2.3/build' failed
make: *** [_module_/var/lib/dkms/u2mfn/3.2.3/build] Error 2
make: Leaving directory '/usr/src/linux-headers-4.9.13-coldkernel-grsec-1'

**Comment by rtiangha** [comment]
I haven't had a chance yet to try to compile a 4.9 kernel under Qubes, but my guess is that the version of u2mfn.c being used is old, based on this message:

`/var/lib/dkms/u2mfn/3.2.3/build/u2mfn.c:80:23: warning: passing argument 5 of ‘get_user_pages’ from incompatible pointer type (data, 1, 1, 0, &user_page, 0);`

It shouldn't be using that function definition. If you look at [the latest version of u2mfn.c](https://github.com/QubesOS/qubes-linux-utils/blob/master/kernel-modules/u2mfn/u2mfn.c) (which was updated in October to compile with 4.9), it has this definition:

`#if LINUX_VERSION_CODE >= KERNEL_VERSION(4, 9, 0)`
`		ret = get_user_pages`
`			(data, 1, (FOLL_WRITE | FOLL_FORCE), &user_page, 0);`
`#elif LINUX_VERSION_CODE >= KERNEL_VERSION(4, 6, 0)`
`		ret = get_user_pages`
`		    (data, 1, 1, 0, &user_page, 0);`
`#else`
`		ret = get_user_pages`
`		    (current, current->mm, data, 1, 1, 0, &user_page, 0);`
`#endif``

That implies to me that the reason why 4.8 kernels were compiling correctly was because in the older version of the file, the middle definition there was the one that was being used first.

So my guess is (and again, I haven't tried this myself yet) that if you were to substitute the latest u2mfn.c file from the QubesOS repo in for whatever one the current iteration of coldkernel is using, then it might compile with kernel 4.9. My question is (since I can't figure it out on my own) is where is coldkernel getting its current copy of u2mfn.c? Is it included in the kernel 4.9 sources, or is it getting pulled in from somewhere? And if so, where?

**Comment by null0x0** [comment]
Case close. You are right about the outdated **u2fmn.c** @rtiangha . I can confirm that Qubes OS still using the old one in **qubes-r3.2-jessie-testing** repo. I re-checked the source and compared to what I have got in all the templates VM. So, either copy or add the proper lines in the u2fmn.c did solved the issue. This is not a coldkernel problem, but definitely Qubes OS using the outdated u2fmn as far as I can confirm. After added the code to the lines, and compile, everything will be fine again. Thanks for the head-up @rtiangha
